### ISSUE TITLE
Allow compiled libraries to load from library-path

### ISSUE THREAD

**Issue by christoff-buerger** [leppie/IronScheme#10]
### Background

I like to support _IronScheme_ in a [bigger _R6RS Scheme_ project](https://github.com/christoff-buerger/racr), that consists of a lot of depending libraries. So far, _Larceny_, _Racket_, _Guile_ and _Petite Chez Scheme_ are supported. Except _Petite_, all of these systems provide means to precompile libraries to speed up the loading and execution time. Of course, each system requires some configuration, such that its virtuell machine can find the precompiled libraries. I developed a bunch of _Bash_ scripts providing a common interface to install my libraries and execute them; thus, to configure the supported _Scheme_ systems.

### Problem

I would like to do the same for _IronScheme_. I tried to use its `compile` function to generate `dll` files and setup its library resolution paths using `library-path`, in particular `(library-path list-of-resolution-paths)`. I am struggling for the following reasons:

 * `compile` saves the `dll` files it generates in _IronScheme's_ root directory (the one the used _IronScheme_ console or _IronScheme.dll_ is in; I am not sure which of both). One of my policies is to not touch anything outside of my project, in particular not to generate or delete files outside of my project. I also would like to save libraries in different directories.
 * Changing the library path via `library-path` seems not to influence `dll` resolution. The precompiled libraries are not found if not in _IronScheme's_ root directory, cluttering it up.

### Question summary

My main concerns are the following:

 1. How are precompiled `dll` libraries resolved?
 2. Is there a way to setup the `dll` resolutions paths similar like `library-path` does for sources?
 3. Are there flags to configure such paths when calling `IronScheme.Console`, such that they can be set outside of the program to run?
 4. Is there a way to compile a single library to a `dll` without _IronScheme_ automatically compiling the transitive closure of its dependencies?
 5. Can the output path, where compiled libraries are generated, be changed? Does `compile` provide further configuration arguments?

### Benefits of a solution

I think it is a natural next step for big projects to move from source code loading to precompiled libraries (assemblies for _.NET_). It would be good if _IronScheme_ supports user build processes with some way to configure generation and loading.

Another advantage is, that I am doing a lot of profiling, comparing major _R6RS Scheme_ systems in a real setup (not small toy-benchmark-programs). My project contains very fast executing examples (less than a second, at most a few seconds), where for example _Guile_ heavily benefits from its fast VM startup and program loading time, up to very heavy computations, running for several minutes, where for example _Larceny_ is a much better choice than _Guile_. It might be interesting for _IronScheme_ to find its place in these scenarios.

**Comment by leppie** [comment]
Hi

Thanks for your questions :)

1. Due to recent library optimizations, all DLL's need to reside in the same directory (for now, I have not found another way yet, but looking).
2. Previously, yes, but with less than optimal libraries. I could investigate allowing the previous behavior.
3. No, all configuration happens within the scheme environment. 
4. No. Macro dependencies should not be needed at runtime, but due to the loader, they are still needed to be there (I am still investigating removing this limitation).
5. No. I am working on solving this currently.

Again, compile is just a scheme procedure. These are the options:
```
; Only in REPL
(compile) ; compiles all loaded libraries
; Not limited to REPL
(compile <program>)
(compile <program> gen-wrapper?)
(compile <program> gen-wrapper? compress-constants?)
; gen-wrapper? generates an exe wrapper (default #f) (not tested for a long time)
; compress-constants? gzips constants (default #t)
```
The `debug-mode?` parameter will also influence if a PDB is emitted (default #f).

If running on Windows, I suggest you use 32-bit console and NGEN IronScheme.dll to get fast startup times (100ms).

Hope I answered most, let me know if you want to know more.

Regards

leppie

**Comment by christoff-buerger** [comment]
Two more questions:

 1. How is the directory the `dll` files are generated into determined? Is it the one the used `IronScheme.Console` resides or the used `IronScheme.dll`?
 2. If I copy all generated `dll` files to a single directory within my project, is it possible to configure _IronScheme_ to use this directory?

Thanks a lot for your fast reply! I assume the library handling is still work in progress and hope my comments are useful feedback.

I will try to setup my compiling and loading infrastructure with the limitations you mention in mind.

**Comment by leppie** [comment]
1. Currently the directory IronScheme.dll resides in
2. Not without IronScheme.dll (and the console exe if needed). I cant recall, but symlinks to it might work, but it will have to be executed from that directory.

The optimizations I got from that is that procedures can be resolved and linked at compile time. Previously, it had to do latebinding at runtime. This also helps the .NET JIT inline small procedures which was not possible previously. 

I have pondered creating library sets (eg for all of (ironscheme ...) or (srfi ...)) that compiles into a single dll, but have not got around to it. (Incidentally, this used to be possible when I used serialized expanded code, but that required the code to be compiled when loaded).

**Comment by christoff-buerger** [comment]
Thanks a lot! I let you know when I got everything running and maybe have first benchmark results.

**Comment by leppie** [comment]
Just a had some time to read, it seems the following is possible:

- I should be able to load DLL's from library path and not just the app dir.
- Compiling DLL's will still be emitted to the app dir, but then can be moved to library path (perhaps can be done automatically?)
- All the dependencies will have to be in a single library path.

Limitations:

- Native images of DLL's in other directories than the app dir will not be loaded (this is not needed really, only IronScheme.dll benefits from this)

I think this should cover most of the issues you have, yes?

Reopening as I want to fix this 'issue' :D

**Comment by christoff-buerger** [comment]
Sounds promising!

> All the dependencies will have to be in a single library path

What does **single** imply? Does it mean that (1) `(library-path)` must evaluate to a single directory, or (2) all `dll` files must be in the first directory of `(library-path)` or (3) **all** `dll` files must be **in one** of the directories of `(library-path)` or (4) all depending `dll` files must be in the same directory, which must be part of `(library-path)` but clusters of depending libraries can be in different directories? Or is it the final solution: _IronScheme_ `dll` files must be in directories of `(library-path)`?

**Comment by leppie** [comment]
It means if you load say `(foo bar baz)` from directory `x`, all the dependencies would need to live in directory `x`. 

Of the options, I would say number 3.

All still theoretical :D 

Been looking at the code, loading DLL's is hardcoded to the app dir currently, but from the information I gathered, it should be possible to load it (and all deps) from another path (aka the first one found in order in library-path).

The problem here is that assembly loading will happen with the CLR runtime. It is not something I can control.

It might even be possible to have number 4 if there is no direct dependency.

**Comment by christoff-buerger** [comment]
**Note:** _I updated my previous comment._

Sounds complicated. From my view point, number (5) would be best. All depending `dll` files in one directory, that has to be part of `library-path` is Ok too. At the moment one could simulate this by copying the _IronScheme.dll_ to the desired directory and use the copy to compile all libraries (assuming only _R6RS_ is used and no further _IronScheme_ functionality. To support (3) would still be an improvement.

**Comment by leppie** [comment]
5 would currently if you create an appdomain to run from there.

This is what `gen-wrapper?` attempts to do, but I cant recall the details now (think you need to have some variable set).

**Comment by christoff-buerger** [comment]
Just a moment I am worried: what do I want? I have to rethink what the implications are :)

**Comment by leppie** [comment]
Either way, I will try allow DLL's to be loaded from a library path :D

**Comment by christoff-buerger** [comment]
Ok, I made up my mind! I want number (5), but not a single configuration file. My project is not a single application, but rather a set of applications (just call them components). Each component consists of a set of libraries that share a common name space. All components depend on a shared core library. Some components depend on other components. Each component has its own binary directory containing its respective compiled binaries (`dll` files in case of _IronScheme_). When executing a component, its binaries and the ones of the components it depends on have to be loaded.

I guess that is sufficient to require a fix :)

**Comment by christoff-buerger** [comment]
> Either way, I will try allow DLL's to be loaded from a library path :D

Thanks! That sounds good!

**Comment by leppie** [comment]
You asked earlier about a command line switch for library paths, there is indeed one already!

Passing `-I <path>` (can be multiple) will add the paths to the library path when running from the standard `IronScheme.Console*.exe`.

**Comment by christoff-buerger** [comment]
I got _IronScheme_ compiling and running in my project! So far, I just copy the _IronScheme_ distribution to a local directory and compile all libraries to `dll` assemblies within that directory.

I did not do big measurements yet, but its about factor 13 slower than _Larceny_ for heavy computations. Don't worry about that; the ability to use stuff from _C#_ itself is worthwhile. I will give more feedback when I find time for more elaborated measurements.

I also got failing test cases. I have an idea what the issue is. I will make another issue for this.

**Comment by leppie** [comment]
IronScheme is quite slow when the generic arithmetic operations are used. You can try use fx/fl ones from R6RS, or if you really want speed, use the typed ones, if you willing to add a few annotations.

**Comment by leppie** [comment]
Should be fixed with https://github.com/leppie/IronScheme/commit/29c36d1d70f05f8c49d79d31a25e626750239e86 (will re-open if CI fails)

**Comment by leppie** [comment]
As an unintended bonus, compiled DLL's will now be emitted to the current working directory :D

**Comment by christoff-buerger** [comment]
> Passing -I <path> (can be multiple) will add the paths to the library path when running from the standard IronScheme.Console*.exe.

That is very helpful!

> As an unintended bonus, compiled DLL's will now be emitted to the current working directory :D

And that too!

Both can be used in a shell script to pinpoint to different destinations for compiled libraries. For example, to compile a _Scheme_ library `my-library` in directory `lib-dir` to a certain directory `output-dir`, whereas `my-library` has dependencies on compiled libraries `dir1/lib1.dll` and `dir2/lib2.dll`:

```
(
cd "output-dir"
echo "(compile \"lib-dir/my-library.sls\")" | \
    "start IronScheme.Console on .NET VM" -I "dir1" -I "dir2"
)
```

**Comment by christoff-buerger** [comment]
I will need a few days before I can try above. But it looks like its solving all my issues :)

**Comment by christoff-buerger** [comment]
> Passing -I <path> (can be multiple) will add the paths to the library path when running from the standard IronScheme.Console*.exe.

Definitely not working!

When I call ```mono `which IronScheme.Console-v4.exe` -I "/usr"``` then `library-path` just is `("." "/Users/cbuerger/Documents/development/ironscheme/lib" "/Users/cbuerger/Documents/development/ironscheme")`.

**Comment by leppie** [comment]
Something is fishy with command line parameter parsing. I will have a look today.

**Comment by christoff-buerger** [comment]
> As an unintended bonus, compiled DLL's will now be emitted to the current working directory :D

Works; also loading `dll` assemblies from `(library-path)` works (commit 29c36d1d70f05f8c49d79d31a25e626750239e86). Thanks!

Just the `-I` parameter is not working for above commit. I am waiting until you give green light about it and then test again. I am using your build link to download the latest build artefacts (https://ci.appveyor.com/project/leppie/ironscheme/branch/master).

**Comment by leppie** [comment]
I will commit a fix today, wanted to finish up some work on pruning unneeded imports first.

**Comment by leppie** [comment]
`-I` Issue fixed in https://github.com/leppie/IronScheme/commit/88ddf91d04a0dc61f433e3f89ce11b19adac3669

**Comment by christoff-buerger** [comment]
Perfect! Thank you very much! The build process is working as intended.

I updated my project's install scripts accordingly (cf. christoff-buerger/racr@7ed091828136f3e7a41dd8c56b3b7d0759037627)

**Comment by leppie** [comment]
BTW, you should not have to copy the binaries anymore now. (I did not check the commit to see if that is what it does)

**Comment by natethern** [comment]
> You asked earlier about a command line switch for library paths, there is indeed one already!
> 
> Passing `-I <path>` (can be multiple) will add the paths to the library path when running from the standard `IronScheme.Console*.exe`.

Is this documented anywhere? I can't seem find documentation for IronScheme anywhere.
