### ISSUE TITLE
Scheme

### ISSUE THREAD

**Issue by khaled1990khaled** [leppie/IronScheme#12]
Hi,

I want to solve this exercise http://acm.up.pt/local/Historial/2002/s2_c.htm

and this is my code so far,

#lang racket
(require racket/block)

(define (print_ls ls)
  (if (empty? ls)
      (display "")
      (block
       (print_code (car ls) 0 1)
       (displayln "")
       (print_ls (cdr ls)))))

(define (print_code ls tab per)
  (if (pair? ls)
      (let ([ln (length ls)])
        (cond
          (equal? ln 2) (if (equal? per 1)
                             (block
                              (print_tab (+ tab 1))
                              (displayin ""))
                             (block
                              (print_tab tab)
                              (displayln (caddr ls))))
                         (if (pair? (caddr ls))
                             (print_code (caddr ls) tab 1)
                             (block
                              (print_tab tab)
                              (display (caddr ls))))
                         (display ")")))))

What is the missing to make the code running?

Thanks

**Comment by leppie** [comment]
Hi, this has nothing to do with IronScheme. In fact you are using Racket.

I suggest you ask on a general Q&A platform like [StackOverflow.com](StackOverflow.com) instead.

Regards

leppie
