### ISSUE TITLE
bitwise-bit-copy and fxbit-copy don't conform to R6RS

### ISSUE THREAD

**Issue by johnwcowan** [leppie/IronScheme#18]
These functions are supposed to have the interface (bitwise-bit-copy dest index source), and set the index'th bit of dest to the index'th bit of source, returning dest.  But IronScheme only accepts 0 and 1 as a source.

**Comment by johnwcowan** [comment]
Ignore the fxbit-copy part of this issue: IronScheme is correct, because bitwise-bit-copy and fxbit-copy are incompatible.

**Comment by leppie** [comment]
Thanks @johnwcowan.

Will have a look.

**Comment by leppie** [comment]
@johnwcowan Not seeing a problem here. The spec says for both the last parameter must be 0 or 1.

http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_1082
http://www.r6rs.org/final/html/r6rs-lib/r6rs-lib-Z-H-12.html#node_idx_932

I assume you mean copy-bit and not bit-copy.

**Comment by johnwcowan** [comment]
Yes, I only saw the erratum after posting the ticket.
