### ISSUE TITLE
Building under Ubuntu 16.04

### ISSUE THREAD

**Issue by ghost** [leppie/IronScheme#21]
Hi, while I'm sure that I have followed all the instructions, i have somehow come to miss some step somewhere to get IronScheme built under Ubuntu 16.04.
What information can I provide you to help you help me get IronScheme up and running under Ubuntu.
Why Ubuntu? Because I got a machine running FreeDOS since I cannot afford a Microsoft Windows license, yet.

**Comment by leppie** [comment]
Sorry for late reply. The only way to build from scratch is on Windows currently. You can however do a bootstrap and compile other scheme code from non-Windows machines.
