### ISSUE TITLE
Trace and untrace procedures

### ISSUE THREAD

**Issue by Toni-zgz** [leppie/IronScheme#25]
Should be posible add trace-lambda, trace-let, trace and untrace in ironscheme as defined in SISC Scheme?

**Comment by tshaug** [comment]
Yes that would be a very cool feature

**Comment by leppie** [comment]
There are a bunch of tracing features already available
```
trace-define
trace-define-syntax
trace-lambda
trace-letrec-syntax
trace-let-syntax
```
And the `trace-printer` parameter which bound by default to `pretty-print`.

**Comment by Toni-zgz** [comment]
It's true. Thanks and good job.

**Comment by tshaug** [comment]
Unlike trace  andf untrace in Racket you can not "activate" tracing afterwards. is that aussumption correct?

**Comment by Toni-zgz** [comment]
@tshaug: I believe that trace and untrace procedures isn't defined. So you only can trace lambdas and syntaxes. I think this is enough to find why your code is failling.
@leppie: is all of this correct?

**Comment by leppie** [comment]
@tshaug Unfortunately that kind of functionality is not available and probably not trivial to implement. If you have a specific issue, and using Windows and have a .NET debugger available, you can always trigger a breakpoint (eg `(clr-static-call System.Diagnostics.Debugger Break)` ) and try inspecting from there (although this is not so easy). You could maybe try tools like dnSpy (https://github.com/0xd4d/dnSpy) too.
