### ISSUE TITLE
Building/upgrading to VS 2017

### ISSUE THREAD

**Issue by advancedwebdeveloper** [leppie/IronScheme#26]
I am trying to upgrade using VS 2017 (15.9.9).

.NET Framework version 4.7.0356.

[IronScheme.zip](https://github.com/leppie/IronScheme/files/3068138/IronScheme.zip)

Switched to Release. Build both .sln files gave such errors:

Metadata file IronScheme.dll not found for IronScheme.Remoting.Server, IronScheme.Web.Runtime;
Metadata file IronScheme.Remoting.Server.dll, IronScheme.Web.Runtime.dll not found for IronScheme.Console
The command "attrib -R "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\IronScheme.y.cs"
attrib -R "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\IronScheme.lex.cs"
"C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\tools\gppg" /gplex "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\IronScheme.y" > "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\IronScheme.y.cs"
"C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\tools\gplex" /stack "/out:C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\IronScheme.lex.cs" "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\IronScheme.lex"
"C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\tools\gppg" /gplex "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\NumberParser.y" > "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\NumberParser.y.cs"
"C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\tools\gplex" /stack "/out:C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\NumberLexer.lex.cs" "C:\Users\Администратор\Desktop\IronScheme-master\IronScheme\IronScheme\Compiler\NumberLexer.lex"" exited with code 3.

**Comment by leppie** [comment]
I just tried it with VS 2017 (15.9.11), Works fine. 

Can you maybe try in a directory that does not contains unicode characters?

**Comment by leppie** [comment]
Closing as you didnt respond, feel fre to reopen.
