### ISSUE TITLE
cKanren instead of minikanren

### ISSUE THREAD

**Issue by Toni-zgz** [leppie/IronScheme#27]
@leppie: Would It Be possible to adapt to Ironscheme the cKanren library from https://github.com/miniKanren/cKanren instead of the miniKanren library that already exists in Ironscheme? It would be a great feature.

**Comment by leppie** [comment]
Yeah, is pretty easy (as with most R6RS scheme code :p ).

1. Copy repo to `lib/cKanren`
2. Rename all .scm files to .sls
3. Find/replace all instances of `chezscheme` and change to `ironscheme`

Then run:
```
> (import (cKanren comptests))
> (run-comptests)
Testing Distinct Queens 1
Testing Distinct Queens 2
Testing infd/Distinct 1
#t
```

That is just the basic test. Ironscheme does not have engines so you need to figure out some other way to test that.

**Comment by Toni-zgz** [comment]
@leppie: Hello 
How can I send you addapted cKanren library to include in Ironscheme stable branch?
Best regards

**Comment by leppie** [comment]
You can do one better and send a PR :D
