### ISSUE TITLE
namespace name 'Glue' could not be found

### ISSUE THREAD

**Issue by abovenyquist** [leppie/IronScheme#29]
@leppie -- I've tried compiling IronScheme in VS 2019, 2017, and 2015. After doing the automatic migrations, setting the starting project to Set IronScheme.Console, and setting the solution profile to release, I always get this build error:

Error	CS0246	The type or namespace name 'Glue' could not be found (are you missing a using directive or an assembly reference?)	IronScheme	C:\Users\Aaron Lanterman\Documents\GitHub\IronScheme\IronScheme\IronScheme\Compiler\Generator.Helpers.cs	21	Active

I also get a bunch of "metadata file XYZ could not be found" errors, which vary depending on which version I'm trying, although I suspect those are symptoms of other issues. 

It looks like Glue is defined in IronScheme.Closures.il, so I suspect the problem is related to these messages that appear on the compiler output log:

IronScheme.Closures -> C:\Users\Aaron Lanterman\Desktop\IronScheme\IronScheme.Closures\bin\Release\IronScheme.Closures.dll
Could not open Lanterman\Desktop\IronScheme\DEVELOPMENT.snk
  
  ***** FAILURE ***** 
IronScheme.Closures.il(92) : error -- Failed to open key file 'C:\Users\Aaron': 0x00000002

**Comment by leppie** [comment]
This is probably related to having spaces in your directory name. 2 options to resolve:

1. Just use a directory without spaces
2. Fix the post build event command to work correctly with spaces (feel free to submit PR if you do this)

**Comment by leppie** [comment]
Fixed in latest commit. Thanks
