### ISSUE TITLE
Up-to-date installer?

### ISSUE THREAD

**Issue by lassik** [leppie/IronScheme#30]
@leppie The Code Project article [Playing with IronScheme](https://www.codeproject.com/articles/33050/playing-with-ironscheme) has a screenshot of a setup program for IronScheme. Is such a setup still available for the latest version, or does IronScheme need to be incorporated into a Visual Studio project?

**Comment by leppie** [comment]
There is no installer, just a zip file. 

I have added it to releases https://github.com/leppie/IronScheme/releases

**Comment by lassik** [comment]
Thanks!
