### ISSUE TITLE
Non-trivial record protocols get a procedure, not an instance

### ISSUE THREAD

**Issue by weinholt** [leppie/IronScheme#33]
Hello @leppie! When a `define-record-type` has a non-trivial `protocol`, it appears that the constructor returns a procedure instead of an instance.

```scheme
(import (rnrs))

(define-record-type foo
  (fields bar (mutable baz))
  (protocol
   (lambda (p)
     (case-lambda
       ((bar)
        (let ((foo (p bar #f)))
          (foo-baz-set! foo bar)
          foo))))))

(display (foo-bar (make-foo 1)))
(newline)
```

The program above should print `1`, but instead it crashes with an assertion:

```
&assertion
&message: "expected type: foo"
&irritants: (#<procedure <RecordConstructor>b__2>)
```

Here is another program that demonstrates the problem:

```scheme
(import (rnrs))

(define-record-type foo
  (fields bar)
  (protocol
   (lambda (p)
     (case-lambda
       ((bar)
        (validate (p bar)))))))

(define (validate x)
  (write x) (newline)
  (assert (foo? x))
  x)

(display (foo-bar (make-foo 1)))
(newline)
```

Changing the `validate` procedure to just return `x` makes the bug go into hiding.

Found with IronScheme 1.0.121-393d598 (.NET 4.0 64-bit) on Mono 5.18.0.240+dfsg-3.

**Comment by leppie** [comment]
Thanks, gonna be tricky to solve. I can't believe how much spaghetti I wrote 10 years ago :D

**Comment by leppie** [comment]
This is going to take a while to fix. I have done some traces on Chez, but the flow is confusing me.

**Comment by leppie** [comment]
Should be fixed in latest release. Let me know if you find more.

**Comment by weinholt** [comment]
Works a lot better now. I have seen a few more bugs, but it will take some effort to track the cause to write good bug reports.

If you're interested, then click the FAILED button on the test-ironscheme builds:

* https://circleci.com/gh/weinholt/semver
* https://circleci.com/gh/weinholt/irc-protocol
* https://circleci.com/gh/weinholt/industria
* https://circleci.com/gh/weinholt/uuid

**Comment by leppie** [comment]
@weinholt No idea what that it ;p The uuid one looks like a broken comparer.

**Comment by leppie** [comment]
@weinholt for industria, you probably need to handle EOF the same for bytevectors than you do for strings. See https://github.com/weinholt/industria/blob/master/ssh/private/serialize.sls#L143

**Comment by weinholt** [comment]
@leppie While there are some things wrong with Industria's code, I'll also open an issue about how IronScheme implements get-bytevector/string-*.

**Comment by leppie** [comment]
> @leppie While there are some things wrong with Industria's code, I'll also open an issue about how IronScheme implements get-bytevector/string-*.

I misinterpreted the spec. It was returning eof when the count was 0 where it should have been empty.

Will push soon.

**Comment by leppie** [comment]
It seems while not allowed by the CLR spec, the CLR is actually possible to do constructor logic like Scheme requires. I have attached a had crafted .NET assembly to show this. 
[ConsoleApp25.zip](https://github.com/leppie/IronScheme/files/3635877/ConsoleApp25.zip)
