### ISSUE TITLE
IronScheme shell command name

### ISSUE THREAD

**Issue by lassik** [leppie/IronScheme#37]
Quoting @leppie from https://github.com/weinholt/scheme-docker/issues/3:

> If you create a symlink to the exe called `isc` it should not print [the logo]. Not sure if this works on Linux though. I will remove the logo if a file has been passed in.

Is `isc` the preferred shell command name for IronScheme? We didn't know this so the current IronScheme wrapper in the Docker container is named `ironscheme`.

There's a tradition of using 3-4 letter commands for Scheme interpreters and compilers, but such short names are somewhat problematic since name clashes are to be expected eventually. Gambit's `gsc` as well as Chicken's `csc` and `csi` already conflict with other non-Scheme software. Based on that precedent, I would recommend just sticking with `ironscheme` which is self-explanatory and bound not to conflict with any other program. Most shells have tab completion for commands nowadays so it's not that much to type.

**Comment by leppie** [comment]
Added `ironscheme` as a known alias to start without logo.

Also if `IronScheme.Console.exe` is run with an existing file, logo will be suppressed. IOW for the following:

- `IronScheme.Console.exe somefile.ss`
- `echo 1 | IronScheme.Console.exe`

**Comment by lassik** [comment]
Perfect. Thanks for responding quickly!
