### ISSUE TITLE
please tell me what licence？

### ISSUE THREAD

**Issue by kerwinxu** [leppie/IronScheme#39]

**Comment by Toni-zgz** [comment]
Microsoft Public License (Ms-PL).
Is in the Ironscheme subdirectory, License file.

**Comment by Toni-zgz** [comment]
License.html file.

**Comment by Toni-zgz** [comment]
@leppie: Could you give more info, please?

**Comment by leppie** [comment]
Only the bits in `IronScheme.Scripting` are under MSPL (the DLR bits).

IronScheme itself is simple BSD https://github.com/leppie/IronScheme/blob/master/IronScheme/IronScheme.Console/docs/license.txt

The libraries included should all have license info attached.
