### ISSUE TITLE
Reader does not recognize \a, \b, \v, \f

### ISSUE THREAD

**Issue by weinholt** [leppie/IronScheme#49]
The reader is missing support for some of the ASCII control character escapes, namely \a, \b, \v and \f.

```scheme
IronScheme 1.0.182-8632bda github.com/leppie/IronScheme © 2007-2019 Llewellyn Pritchard (.NET 4.0 64-bit)
> (string-length "\a\b\v\f")        
8
```

The expected output is 4.

I checked your lexer and it very obviously doesn't have this bug. Interesting!

```Yacc
single_string_char     [^\\\"\n\r]
string_esc_seq         (\\[\"\\abfnrtv])
```

(This is causing the test failure in weinholt/laesare).

**Comment by leppie** [comment]
Release created
