### ISSUE TITLE
Hashtables don't accept empty list as key.

### ISSUE THREAD

**Issue by 2bt** [leppie/IronScheme#5]
To my understanding this programme conforms with r6rs and it runs without problems in racket. IronScheme throws an exception.

	(import (rnrs))
	(hashtable-ref (make-eq-hashtable) '() 'default)

**Comment by 2bt** [comment]
In the meantime, I've been doing something like this:

     (define-record-type nil-record (sealed #t) (opaque #t))
     (define nil (make-nil-record))
    
     (define hashtable-ref*
       (lambda (h k d)
         (hashtable-ref h (if (null? k) nil k) d)))
    
     (define hashtable-set!*
       (lambda (h k v)
         (hashtable-set! h (if (null? k) nil k) v)))
    
     (define hashtable-delete!*
       (lambda (h k)
         (hashtable-delete! h (if (null? k) nil k))))
    
     (define hashtable-contains?*
       (lambda (h k)
         (hashtable-contains? h (if (null? k) nil k))))
    
     (define hashtable-entries*
       (lambda (h)
         (let-values
           (((kv vv) (hashtable-entries h)))
           (let ((n (vector-length kv)))
                 (do ([i 0 (+ i 1)])
                     ((= i n))
                   (when (eq? (vector-ref kv i) nil) (vector-set! kv i '()))))
           (values kv vv)))))

You're right. It feels very hacky and I'm not happy with it. But I need this behaviour of a project. Do you maybe have a better idea? Great work, btw.

**Comment by leppie** [comment]
That's about right.

You could probably use `vector-map` instead of the `do` in the last proc.

**Comment by christoff-buerger** [comment]
> I will think about it a bit more.

Will this be fixed or does...

> I could work around it, by creating some substitute for null but it seems hacky, and then you have differences in behavior between .NET and IronScheme which I try my best to avoid.

...outweigh _R6RS_ conformance?

At the moment I use boilerplate code like above to create a special nil-record used in case of empty lists as keys. Its bothersome and fragile however, to maintain several product versions for different _Scheme_ implementations.

**Comment by leppie** [comment]
I was thinking of building it into IronScheme libraries, but need to investigate. I think some hashtable procedure(s) are still done in C# which makes it tricky.

**Comment by leppie** [comment]
@christoff-buerger Should be fixed in last commit, let me know if you pick up issues.

**Comment by christoff-buerger** [comment]
Works! Thanks a lot!
