### ISSUE TITLE
make-string, open-string-input-port and UTF-8

### ISSUE THREAD

**Issue by lassik** [leppie/IronScheme#50]
Latest release:

```
> (open-string-input-port "a")
#<textual-input-port>
> (open-string-input-port "ä")
#<textual-input-port>
> (open-string-input-port (make-string 1 (integer->char 127)))
Unhandled CLR exception during evaluation:
CLR Exception: System.InvalidCastException
System.InvalidCastException: Specified cast is not valid.
  at #.ironscheme.io.ports::open-string-input-port (System.Object str) [0x0003f] in <16cd200c5d96470892323901f0226e81>:0
> (string-ref (make-string 1 (integer->char 127)) 0)
#\delete
> (bytevector-length (string->utf8 (make-string 1 (integer->char 127))))
1
> (bytevector-u8-ref (string->utf8 (make-string 1 (integer->char 127))) 0)
127
```

**Comment by leppie** [comment]
Thanks fixed. 

The only issue here is with `(open-string-input-port (make-string 1 (integer->char 127)))`.

127 is single byte encoded in utf8.

**Comment by lassik** [comment]
That was fast, thank you! You're right. I checked the string->bytevector encodings because I was testing the boundary values 127 and 128 in different Schemes. The UTF-8 encoding seems to be working fine in IronScheme :) 128 is encoded as 2 bytes, as it should be.

**Comment by lassik** [comment]
I'm using `open-string-input-port` to iterate over the characters in a string since `string-ref` is slow in some Schemes. Is it the way to go in IronScheme as well?

**Comment by leppie** [comment]
`string-ref` is fast (O(1)), but no support for unicode code points above `0xffff`.

**Comment by lassik** [comment]
Is that since .NET uses UTF-16 with internally and the `string-ref` implementation doesn't decode surrogate pairs?

**Comment by leppie** [comment]
that is correct
