### ISSUE TITLE
Whitespace in character literals

### ISSUE THREAD

**Issue by lassik** [leppie/IronScheme#51]
I have some failing test cases that I suspect are caused by how the IronScheme reader treats `#\` followed by a tab or a newline. It turns them into `#\space` I think. If my reading (no pun intended) of R6RS is correct, it should preserve the tab or newline.

Admittedly, using raw tabs or newlines in character literals is pretty terrible practice, but I suppose the standard says it should work anyway. I auto-convert some code from R7RS to R6RS, that's why they end up in there...

**Comment by leppie** [comment]
Hi

Is this what you mean?

```
> (read (open-string-input-port "#\\\t"))
#\tab
> (read (open-string-input-port "#\\\n"))
#\space
```

**Comment by lassik** [comment]
I think that's exactly it. So the second example should return `#\newline` instead, which ought to be fixed by the commit you just made. Also `(read (open-string-input-port "#\\ "))` should return `#\space`, which it already seems to do.

I'm not well versed in the details of R6RS, so this is just my impression.

**Comment by leppie** [comment]
Thanks :D

**Comment by lassik** [comment]
No problem :) Thanks for taking great care of your implementation!

**Comment by lassik** [comment]
For reference, here's what Chez Scheme does:

```
> (read (open-string-input-port "#\\ "))
#\space
> (read (open-string-input-port "#\\\t"))
#\tab
> (read (open-string-input-port "#\\\n"))
#\newline
```

**Comment by leppie** [comment]
> For reference, here's what Chez Scheme does:

Exactly what I tested with :D

**Comment by lassik** [comment]
:D
