### ISSUE TITLE
string->list eats combining characters

### ISSUE THREAD

**Issue by weinholt** [leppie/IronScheme#55]
The `string->list` procedure in IronScheme eats the U+094B DEVANAGARI VOWEL SIGN O character:

```scheme
> (string #\x0932 #\x094B)
"लो"
> (string-length (string #\x0932 #\x094B))
2
> (list->string '(#\x0932 #\x094B))
"लो"
; So far so good. But with string->list, things start to go wrong:
> (length (string->list (string #\x0932 #\x094b)))
1
> (list->string (string->list (string #\x0932 #\x094B)))
"ल"
> (map char->integer (string->list (string #\x0932 #\x094B)))
(2354)   ;#x0932
```

Tested with IronScheme 1.0.212-dfc3528 on both .NET Core 3.0 64-bit and Mono .NET 4.0 64-bit. Found in Industria's punycode test suite.

**Comment by leppie** [comment]
Thanks. Cannot repro in Windows. Will check my Ubuntu VM.

**Comment by leppie** [comment]
Upstream ubg: https://github.com/dotnet/coreclr/issues/27944

**Comment by leppie** [comment]
According to the dotnet dev, the correct answer is 1. I dont know anything about Unicode really, but I did question why. Any opinions on what the actual correct answer is?

**Comment by leppie** [comment]
Seems I understood the functionality I am calling incorrectly. (the code I am calling act on grapheme and not code points)

**Comment by weinholt** [comment]
The joys of code reuse. :)

All Industria's tests pass on IronScheme with .NET Core now. Good stuff. Top quality Scheme.

**Comment by leppie** [comment]
> The joys of code reuse. :)
> 
> All Industria's tests pass on IronScheme with .NET Core now. Good stuff. Top quality Scheme.

Thanks!

It is not that slow either given given IronScheme is generally slow with arithmetic stuff.
