### ISSUE TITLE
Are PCL profiles supported?

### ISSUE THREAD

**Issue by olsonjeffery** [leppie/IronScheme#7]
I'm not sure if you can use the DLR in PCL libraries (profiles 158 & 78 are what I'm using). Do you know if it's possible?

If not, I can do the research and update this issue as necessary, possibly doing a PR to add support.

**Comment by leppie** [comment]
Last I checked this was not possible due to the lack of most of the stuff needed in `System.Reflection.Emit`. This was years ago, so if stuff has changed, maybe it can be made to work.

**Comment by leppie** [comment]
Today still CoreCLR is too 'weak' to support IronScheme. F# has similar problems. Maybe one day...

**Comment by leppie** [comment]
Superceded by https://github.com/leppie/IronScheme/issues/19
