### ISSUE TITLE
evaluation of continuation fails

### ISSUE THREAD

**Issue by tshaug** [leppie/IronScheme#8]
Hi 
I started to use IronScheme (great stuff by the way, thank you for sharing) to "re-new" my scheme knowhow. 
I am trying to understand continuations by reading "The Scheme Programming Language", second edition since my copy of Abelson Sussmann SICP does not seem to discuss that feature. 

When I try to execute 
(let ((x (call/cc (lambda (k) k))))  ;; x local vars
	(x (lambda (ignore) "hi")))    ;; body

I get the following error in IronScheme console and/or the VS plugin:
&assertion
&who: "call/cc"
&message: "not supported, continuation called outside dynamic extent"
&irritants: ()

Gambit and DrRacket (with Scheme language) return the correct result "hi" as described in the first mentioned book on page 62.

**Comment by leppie** [comment]
As mentioned this is not supported in IronScheme. You can only use `call/cc` as an escape continuation. If you really need such support, I suggest using a Scheme which does support it :)

**Comment by tshaug** [comment]
Hi Leppie,

thank you for your reponse. 
I wasn't sure if that is a bug or a feature. That's why I created the ticket.

Once again thanks for the clarification.

Kind regards
Thomas
